# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    

https://colab.research.google.com/drive/1vGF7XFDZvrDnWCi4qtoEHOI2g3WSnEWD
"""

#!/usr/bin/env python
# coding: utf-8

# In[ ]:


import numpy as np
import joblib
from flask import Flask,render_template,url_for,request
import pandas as pd 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import svm


app = Flask(__name__)
model = joblib.load('svm_model.pkl')
vectorizer=joblib.load('SVM_vectorizer.pkl')


@app.route('/')
def home():
    return render_template('index.html')


@app.route('/predict',methods=['POST'])
def predict():
    if request.method == 'POST':
       message = request.form['message']
       data = [message]
       class_dict = {0: 'letter', 1: 'form', 2: 'invoice', 3: 'advertisement', 4:'email'}
       vect = vectorizer.transform(data).toarray()
       my_prediction = model.predict(vect)
       result = class_dict[my_prediction[0]]
    return render_template('index.html', prediction_text='Predicted Document is of type: {}'.format(result))

if __name__ == "__main__":
    app.run(debug=True)
